# Generated by Django 5.2.1 on 2025-07-21 17:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_audituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Nombre del icono (emoji o clase CSS)', max_length=50)),
                ('category', models.CharField(choices=[('study', 'Estudio'), ('tasks', 'Tareas'), ('social', 'Social'), ('streak', 'Racha'), ('special', 'Especial')], max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'security_achievement',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve descripción sobre ti', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Días consecutivos de actividad'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_adhd',
            field=models.BooleanField(default=False, help_text='¿Tienes TDAH? Esto nos ayuda a personalizar tu experiencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='Nombre de tu institución educativa', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_streak_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditivo'), ('kinesthetic', 'Kinestésico'), ('reading_writing', 'Lectoescritor'), ('mixed', 'Mixto')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, help_text='Carrera o área de estudio', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='notes_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_study_time',
            field=models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('evening', 'Noche'), ('late_night', 'Madrugada')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_level',
            field=models.CharField(choices=[('high_school', 'Bachillerato'), ('university', 'Universidad'), ('technical', 'Técnico'), ('postgraduate', 'Postgrado'), ('self_learning', 'Autoaprendizaje')], default='university', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_field',
            field=models.CharField(default='America/Guayaquil', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='total_study_time',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo total de estudio en minutos'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('autodidact', 'Autodidacta'), ('professional', 'Profesional'), ('admin', 'Administrador')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver')], max_length=15, verbose_name='Accion'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pomodoro_duration', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('default_break_duration', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_view', models.BooleanField(default=False)),
                ('show_motivational_quotes', models.BooleanField(default=True)),
                ('ai_assistance_level', models.CharField(choices=[('minimal', 'Mínima'), ('moderate', 'Moderada'), ('full', 'Completa')], default='moderate', max_length=20)),
                ('auto_generate_summaries', models.BooleanField(default=True)),
                ('study_reminders', models.BooleanField(default=True)),
                ('task_deadlines', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
                'db_table': 'security_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'db_table': 'security_user_achievement',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
