# Generated by Django 5.2.1 on 2025-07-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_userachievement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
