# Generated by Django 5.2.1 on 2025-07-22 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_level',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Días consecutivos de actividad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='¿Correo verificado? True si viene de OAuth.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='es', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditivo'), ('kinesthetic', 'Kinestésico'), ('reading_writing', 'Lectoescritor'), ('mixed', 'Mixto')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='notes_created',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_study_time',
            field=models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('evening', 'Noche'), ('late_night', 'Madrugada')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_level',
            field=models.CharField(blank=True, choices=[('high_school', 'Bachillerato'), ('university', 'Universidad'), ('technical', 'Técnico'), ('postgraduate', 'Postgrado'), ('self_learning', 'Autoaprendizaje')], default='university', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks_completed',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone_field',
            field=models.CharField(blank=True, default='America/Guayaquil', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_study_time',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo total de estudio en minutos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Estudiante'), ('autodidact', 'Autodidacta'), ('professional', 'Profesional'), ('admin', 'Administrador')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario único. Si no se ingresa, se autogenera desde el email.', max_length=150, null=True, unique=True),
        ),
    ]
