# Generated by Django 5.2.1 on 2025-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_user_user_uuid_alter_user_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='¿Completó el onboarding?'),
        ),
    ]
