# Generated by Django 5.2.1 on 2025-07-29 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievement_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_assistance_level',
            field=models.CharField(choices=[('minimal', 'Mínima'), ('moderate', 'Moderada'), ('full', 'Completa')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_generate_summaries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_start_breaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='compact_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='default_break_duration',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='user',
            name='default_pomodoro_duration',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='user',
            name='show_motivational_quotes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='task_deadlines',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
