version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=visionpulse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Configuración importante para permitir conexiones externas
    command: postgres -c listen_addresses='*'

volumes:
  postgres_data: