# Generated by Django 5.2.1 on 2025-10-26 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_user_blink_rate_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_overlay_blur_sigma',
            field=models.PositiveSmallIntegerField(default=9, help_text='Cantidad de desenfoque del glow (1-20). Menor valor = más rápido.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Sigma Desenfoque Overlay'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_overlay_enabled',
            field=models.BooleanField(default=True, help_text='Mostrar el óvalo verde sobre el rostro detectado. Desactivar en dispositivos de gama baja.', verbose_name='Overlay Facial Habilitado'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_overlay_glow_intensity',
            field=models.FloatField(default=0.6, help_text='Intensidad del brillo del óvalo facial (0.0-1.0). Menor valor = menos GPU.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Intensidad Brillo Overlay'),
        ),
    ]
