# Generated by Django 5.2.1 on 2025-10-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_add_face_overlay_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='breaks_taken',
        ),
    ]
