# Generated by Django 5.2.1 on 2025-10-31 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0005_remove_user_alert_volume_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserMonitoringConfig",
        ),
    ]
