# Generated by Django 5.2.1 on 2025-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_user_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, help_text='Nombre de usuario único. Obligatorio.', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
