# Generated by Django 5.2.1 on 2025-11-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_user_notification_sound"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="longest_streak",
            field=models.PositiveIntegerField(
                default=0, help_text="Racha más larga de días consecutivos"
            ),
        ),
    ]
