# Generated by Django 5.2.1 on 2025-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
    ]
