# Generated by Django 5.2.1 on 2025-11-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_migrate_monitoring_fields_to_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ear_threshold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_blink_rate_threshold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='low_blink_rate_threshold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='low_light_threshold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yawn_mar_threshold',
        ),
    ]
