# Generated by Django 5.2.1 on 2025-07-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_user_achievement_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_adhd',
        ),
    ]
