# Generated by Django 5.2.1 on 2025-09-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_apikey_remove_user_achievement_notifications_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
