# Generated by Django 5.2.1 on 2025-10-16 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_pause_on_fatigue',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_suggest_exercises',
        ),
        migrations.RemoveField(
            model_name='user',
            name='break_reminders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exercise_difficulty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visual_fatigue_alerts',
        ),
        migrations.AddField(
            model_name='user',
            name='alert_volume',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymous_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blink_rate_threshold',
            field=models.PositiveIntegerField(default=15, help_text='Parpadeos mínimos por minuto para alerta', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='user',
            name='blink_window_frames',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ventana confirmación (frames)'),
        ),
        migrations.AddField(
            model_name='user',
            name='camera_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='data_collection_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ear_threshold',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.4)], verbose_name='Umbral EAR'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_detection_sensitivity',
            field=models.FloatField(default=0.7, help_text='Sensibilidad de detección facial (0.1-1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='fatigue_threshold',
            field=models.FloatField(default=0.7, help_text='Umbral para alertas de fatiga (0.1-1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, default='es', max_length=10, verbose_name='Idioma/Localización'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_mode',
            field=models.CharField(choices=[('visual', 'Visual'), ('sound', 'Sonora'), ('both', 'Ambos'), ('none', 'Ninguno')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_inactive_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sampling_interval_seconds',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='America/Guayaquil', max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='security/users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_monitoring_time',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo total monitoreado en minutos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Nombre de usuario único. Se autogenera desde el email si no se proporciona.', max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
