# Generated by Django 5.2.1 on 2025-09-19 03:31

import apps.exercises.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('med', 'Media'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.exercises.models.exercise_video_upload_to)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='exercises/icons/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio Ocular',
                'verbose_name_plural': 'Ejercicios Oculares',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Ejercicio',
                'verbose_name_plural': 'Sesiones de Ejercicio',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='exercises_e_user_id_08f238_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('instruction', models.CharField(max_length=400)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Paso de Ejercicio',
                'verbose_name_plural': 'Pasos de Ejercicio',
                'ordering': ['order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
    ]
