# Generated by Django 5.2.1 on 2025-10-18 20:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Una descripción corta para la tarjeta del catálogo.', verbose_name='Descripción')),
                ('icon_class', models.CharField(help_text='Ej: "fas fa-eye". El ícono para el catálogo.', max_length=50, verbose_name='Clase del Icono (FontAwesome)')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca esto para ocultar el ejercicio del catálogo.', verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='El orden en que este paso aparecerá (1, 2, 3...).', verbose_name='Orden del Paso')),
                ('instruction', models.CharField(help_text='La instrucción que el usuario debe seguir.', max_length=255, verbose_name='Instrucción')),
                ('icon_class', models.CharField(help_text='Ej: "fas fa-sync-alt fa-spin". El ícono que se mostrará durante este paso.', max_length=50, verbose_name='Clase del Icono de Animación (FontAwesome)')),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración del paso (segundos)')),
            ],
            options={
                'verbose_name': 'Paso del Ejercicio',
                'verbose_name_plural': 'Pasos del Ejercicio',
                'ordering': ['exercise', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calificación')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exercises.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Sesión de Ejercicio',
                'verbose_name_plural': 'Sesiones de Ejercicios',
                'ordering': ['-started_at'],
            },
        ),
    ]
