# Generated by Django 5.2.1 on 2025-10-17 15:06

import apps.exercises.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['title'], 'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='exercisesession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Sesión de Ejercicio', 'verbose_name_plural': 'Sesiones de Ejercicios'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='exercisesession',
            name='notes',
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Duración estimada del ejercicio en minutos', verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction_steps',
            field=models.TextField(default='', help_text='Instrucciones paso a paso del ejercicio', verbose_name='Instrucciones'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('parpadeo', 'Ejercicio de Parpadeo'), ('enfoque', 'Ejercicio de Enfoque'), ('movimiento', 'Ejercicio de Movimiento'), ('relajacion', 'Ejercicio de Relajación')], default='movimiento', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Retroalimentación'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('med', 'Media'), ('hard', 'Difícil')], default='easy', max_length=10, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/icons/', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.exercises.models.exercise_video_upload_to, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exercises.exercise', verbose_name='Ejercicio'),
        ),
        migrations.DeleteModel(
            name='ExerciseStep',
        ),
    ]
