# Generated by Django 5.2.1 on 2025-10-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisestep',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercises.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['user', 'started_at'], name='exercises_e_user_id_08f238_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisestep',
            unique_together={('exercise', 'step_order')},
        ),
    ]
