# Generated by Django 5.2.1 on 2025-10-24 16:01

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indica si se completó todo el ejercicio', verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='feedback',
            field=models.TextField(blank=True, help_text='Comentarios del usuario sobre el ejercicio', verbose_name='Retroalimentación'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐ 1'), (2, '⭐ 2'), (3, '⭐ 3'), (4, '⭐ 4'), (5, '⭐ 5')], help_text='Calificación del 1 al 5', null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['completed', 'started_at'], name='exercises_e_complet_ba2619_idx'),
        ),
    ]
