# Generated by Django 5.2.1 on 2025-10-25 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_created_at_exercise_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisestep',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='exercisestep',
            name='video_clip',
            field=models.FileField(blank=True, help_text='Sube un clip corto que muestre la animación del paso (MP4, WebM u OGG).', max_length=500, null=True, upload_to='exercises/steps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Clip de Video del Paso'),
        ),
    ]
