# Generated by Django 5.2.1 on 2025-11-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_exercisestep_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesession',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐ 1'), (2, '⭐ 2'), (3, '⭐ 3'), (4, '⭐ 4'), (5, '⭐ 5')], help_text='Calificación del 1 al 5 estrellas', null=True, verbose_name='Calificación'),
        ),
    ]
