# Generated by Django 5.2.1 on 2025-09-19 03:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),  # Actualizado para usar la migración inicial de security
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_blinks', models.PositiveIntegerField(default=0)),
                ('avg_ear', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('focus_percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('alerts_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, help_text='Metadatos: device info, sampling rate, client-version', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.cameradevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Monitoreo',
                'verbose_name_plural': 'Sesiones de Monitoreo',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blink_events', to='monitoring.monitorsession')),
            ],
            options={
                'verbose_name': 'Evento de Parpadeo',
                'verbose_name_plural': 'Eventos de Parpadeo',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distract', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('camera_lost', 'Cámara perdida')], max_length=30)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Detalles: avg_ear, window_frames, sample_rate', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitorsession')),
            ],
            options={
                'verbose_name': 'Evento de Alerta',
                'verbose_name_plural': 'Eventos de Alerta',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitorsession',
            index=models.Index(fields=['user', 'start_time'], name='monitoring__user_id_118282_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorsession',
            index=models.Index(fields=['created_at'], name='monitoring__created_25480f_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkevent',
            index=models.Index(fields=['session', 'timestamp'], name='monitoring__session_a22f66_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['session', 'alert_type', 'triggered_at'], name='monitoring__session_2ab067_idx'),
        ),
    ]
