# Generated by Django 5.2.1 on 2025-10-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsession',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.cameradevice'),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blinkevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blink_events', to='monitoring.monitorsession'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitorsession'),
        ),
        migrations.AddIndex(
            model_name='monitorsession',
            index=models.Index(fields=['user', 'start_time'], name='monitoring__user_id_118282_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorsession',
            index=models.Index(fields=['created_at'], name='monitoring__created_25480f_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkevent',
            index=models.Index(fields=['session', 'timestamp'], name='monitoring__session_a22f66_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['session', 'alert_type', 'triggered_at'], name='monitoring__session_2ab067_idx'),
        ),
    ]
