# Generated by Django 5.2.1 on 2025-10-22 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pause_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("resume_time", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="monitoring.monitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pausa de Sesión",
                "verbose_name_plural": "Pausas de Sesión",
                "ordering": ["pause_time"],
                "indexes": [
                    models.Index(
                        fields=["session", "pause_time"],
                        name="monitoring__session_b5659f_idx",
                    )
                ],
            },
        ),
    ]
