# Generated by Django 5.2.1 on 2025-10-23 17:14

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_sessionpause'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='effective_duration',
            field=models.FloatField(default=0.0, help_text='Duración efectiva excluyendo pausas'),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='final_metrics',
            field=models.JSONField(blank=True, help_text='Métricas finales al terminar la sesión', null=True),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='focus_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='pause_duration',
            field=models.FloatField(default=0.0, help_text='Duración total de pausas'),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('completed', 'Completada'), ('interrupted', 'Interrumpida')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='total_alerts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='total_duration',
            field=models.FloatField(default=0.0, help_text='Duración total en segundos'),
        ),
        migrations.AddIndex(
            model_name='monitorsession',
            index=models.Index(fields=['status'], name='monitoring__status_837707_idx'),
        ),
    ]
