# Generated by Django 5.2.1 on 2025-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alertevent_level_alertevent_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='alert_type',
            field=models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distraction', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('microsleep', 'Microsueño detectado'), ('yawn', 'Bostezo detectado'), ('low_blink_rate', 'Tasa de parpadeo baja'), ('high_blink_rate', 'Tasa de parpadeo alta'), ('frequent_distraction', 'Distracción frecuente (ráfagas)'), ('phone_use', 'Posible uso de celular'), ('postural_rigidity', 'Rigidez postural / Mirada fija'), ('head_agitation', 'Movimiento excesivo de cabeza'), ('driver_absent', 'Usuario ausente'), ('multiple_people', 'Múltiples personas detectadas'), ('camera_occluded', 'Cámara obstruida'), ('camera_lost', 'Cámara perdida')], max_length=30),
        ),
    ]
