# Generated by Django 5.2.1 on 2025-10-25 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_alertevent_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distraction', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('microsleep', 'Microsueño detectado'), ('yawn', 'Bostezo detectado'), ('low_blink_rate', 'Tasa de parpadeo baja'), ('high_blink_rate', 'Tasa de parpadeo alta'), ('frequent_distraction', 'Distracción frecuente (ráfagas)'), ('phone_use', 'Posible uso de celular'), ('postural_rigidity', 'Rigidez postural / Mirada fija'), ('head_agitation', 'Movimiento excesivo de cabeza'), ('driver_absent', 'Usuario ausente'), ('multiple_people', 'Múltiples personas detectadas'), ('camera_occluded', 'Cámara obstruida'), ('camera_lost', 'Cámara perdida')], max_length=30, unique=True)),
                ('default_voice_clip', models.FileField(blank=True, help_text='Audio por defecto para este tipo de alerta.', max_length=500, null=True, upload_to='monitoring/alerts/types/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Audio por defecto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config Tipo de Alerta',
                'verbose_name_plural': 'Configs Tipos de Alerta',
                'ordering': ['alert_type'],
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='voice_clip',
            field=models.FileField(blank=True, help_text='Audio de voz a reproducir cuando se genera la alerta.', max_length=500, null=True, upload_to='monitoring/alerts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Audio de alerta'),
        ),
    ]
