# Generated by Django 5.2.1 on 2025-10-26 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alerttypeconfig_alertevent_voice_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsession',
            name='avg_brightness',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(255.0)]),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='avg_head_pitch',
            field=models.FloatField(blank=True, help_text='Pitch promedio en grados', null=True),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='avg_head_roll',
            field=models.FloatField(blank=True, help_text='Roll promedio en grados', null=True),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='avg_head_yaw',
            field=models.FloatField(blank=True, help_text='Yaw promedio en grados', null=True),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='avg_mar',
            field=models.FloatField(blank=True, help_text='MAR promedio (Mouth Aspect Ratio)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='detection_rate',
            field=models.FloatField(blank=True, help_text='Porcentaje de frames con detección exitosa', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='head_pose_variance',
            field=models.FloatField(blank=True, help_text='Varianza de postura de cabeza', null=True),
        ),
        migrations.AddField(
            model_name='monitorsession',
            name='total_yawns',
            field=models.PositiveIntegerField(default=0, help_text='Total de bostezos detectados'),
        ),
    ]
