# Generated by Django 5.2.1 on 2025-10-26 13:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_monitorsession_avg_brightness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_tracking_enabled', models.BooleanField(default=False, help_text='Usa L2CS-Net para detectar dirección de mirada (requiere más CPU/GPU)', verbose_name='Activar Gaze Tracking')),
                ('gaze_threshold_yaw', models.FloatField(default=15.0, help_text='Ángulo máximo horizontal para considerar "atento" (grados)', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral Yaw para Atención')),
                ('gaze_threshold_pitch', models.FloatField(default=15.0, help_text='Ángulo máximo vertical para considerar "atento" (grados)', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral Pitch para Atención')),
                ('yawn_cnn_enabled', models.BooleanField(default=False, help_text='Usa modelo CNN entrenado para detectar bostezos (más preciso pero requiere GPU)', verbose_name='Activar CNN de Bostezos')),
                ('yawn_cnn_model_path', models.CharField(blank=True, default='models/yawn_detector.h5', help_text='Ruta al archivo .h5 del modelo entrenado', max_length=500, verbose_name='Ruta del Modelo CNN')),
                ('yawn_cnn_confidence_threshold', models.FloatField(default=0.7, help_text='Confianza mínima para considerar bostezo (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral de Confianza CNN')),
                ('yawn_fusion_mode', models.CharField(choices=[('mar_only', 'Solo MAR (actual)'), ('cnn_only', 'Solo CNN'), ('or_logic', 'MAR O CNN'), ('and_logic', 'MAR Y CNN')], default='mar_only', help_text='Cómo combinar detección MAR con CNN', max_length=20, verbose_name='Modo de Fusión MAR+CNN')),
                ('phone_detection_enabled', models.BooleanField(default=False, help_text='Usa YOLOv8 para detectar celular en frame (recomendado)', verbose_name='Activar Detección YOLO')),
                ('phone_yolo_model', models.CharField(choices=[('yolov8n.pt', 'YOLOv8 Nano (rápido)'), ('yolov8s.pt', 'YOLOv8 Small (equilibrado)'), ('yolov8m.pt', 'YOLOv8 Medium (preciso)')], default='yolov8n.pt', help_text='Modelo YOLO a usar (nano recomendado)', max_length=50, verbose_name='Modelo YOLO')),
                ('phone_confidence_threshold', models.FloatField(default=0.5, help_text='Confianza mínima para detectar celular', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral Confianza YOLO')),
                ('fallback_to_basic', models.BooleanField(default=True, help_text='Si modelo mejorado falla, usar detección básica', verbose_name='Fallback Automático')),
                ('max_inference_time_ms', models.IntegerField(default=150, help_text='Si un modelo tarda más, se desactiva', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Tiempo Máximo de Inferencia (ms)')),
                ('log_model_performance', models.BooleanField(default=False, help_text='Guardar métricas de rendimiento (para debugging)', verbose_name='Loggear Rendimiento')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='Histórico de tiempos de inferencia', verbose_name='Métricas de Rendimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario dueño de esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_model_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Modelos Mejorados',
                'verbose_name_plural': 'Configuraciones de Modelos Mejorados',
            },
        ),
    ]
