# Generated by Django 5.2.1 on 2025-10-26 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_enhancedmodelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_detection_enabled_default', models.BooleanField(default=False, verbose_name='YOLO activado por defecto')),
                ('yawn_cnn_enabled_default', models.BooleanField(default=False, verbose_name='CNN bostezos activado por defecto')),
                ('gaze_tracking_enabled_default', models.BooleanField(default=False, verbose_name='Gaze activado por defecto')),
                ('phone_yolo_model_default', models.CharField(choices=[('yolov8n.pt', 'YOLOv8 Nano (rápido)'), ('yolov8s.pt', 'YOLOv8 Small (equilibrado)'), ('yolov8m.pt', 'YOLOv8 Medium (preciso)')], default='yolov8n.pt', max_length=50, verbose_name='Modelo YOLO por defecto')),
                ('phone_confidence_threshold_default', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral confianza YOLO por defecto')),
                ('yawn_cnn_confidence_threshold_default', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral confianza CNN por defecto')),
                ('yawn_fusion_mode_default', models.CharField(choices=[('mar_only', 'Solo MAR (actual)'), ('cnn_only', 'Solo CNN'), ('or_logic', 'MAR O CNN'), ('and_logic', 'MAR Y CNN')], default='mar_only', max_length=20, verbose_name='Modo fusión por defecto')),
                ('gaze_threshold_yaw_default', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral yaw Gaze por defecto')),
                ('gaze_threshold_pitch_default', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral pitch Gaze por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('version', models.CharField(blank=True, default='v1', max_length=20, verbose_name='Versión')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defaults de Modelos Mejorados',
                'verbose_name_plural': 'Defaults de Modelos Mejorados',
                'ordering': ['-updated_at'],
            },
        ),
    ]
