# Generated by Django 5.2.1 on 2025-10-26 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_modeldefaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_tracking_enabled', models.BooleanField(default=False, help_text='Usa L2CS-Net (requiere más CPU/GPU)', verbose_name='Activar Gaze Tracking')),
                ('gaze_threshold_yaw', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral Yaw Gaze')),
                ('gaze_threshold_pitch', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Umbral Pitch Gaze')),
                ('yawn_cnn_enabled', models.BooleanField(default=False, help_text='Usa modelo CNN (más preciso pero requiere GPU)', verbose_name='Activar CNN de Bostezos')),
                ('yawn_cnn_model_path', models.CharField(blank=True, default='models/yawn_detector.h5', help_text='Ruta al archivo .h5 del modelo entrenado', max_length=500, verbose_name='Ruta del Modelo CNN')),
                ('yawn_cnn_confidence_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral Confianza CNN')),
                ('yawn_fusion_mode', models.CharField(choices=[('mar_only', 'Solo MAR (actual)'), ('cnn_only', 'Solo CNN'), ('or_logic', 'MAR O CNN'), ('and_logic', 'MAR Y CNN')], default='mar_only', max_length=20, verbose_name='Modo de Fusión MAR+CNN')),
                ('phone_detection_enabled', models.BooleanField(default=True, help_text='Usa YOLOv8 para detectar celular (recomendado)', verbose_name='Activar Detección YOLO')),
                ('phone_yolo_model', models.CharField(choices=[('yolov8n.pt', 'YOLOv8 Nano (rápido)'), ('yolov8s.pt', 'YOLOv8 Small (equilibrado)'), ('yolov8m.pt', 'YOLOv8 Medium (preciso)')], default='yolov8m.pt', help_text='Modelo YOLO a usar', max_length=50, verbose_name='Modelo YOLO')),
                ('phone_confidence_threshold', models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)], verbose_name='Umbral Confianza YOLO')),
                ('fallback_to_basic', models.BooleanField(default=True, help_text='Si modelo mejorado falla, usar detección básica', verbose_name='Fallback Automático')),
                ('max_inference_time_ms', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Tiempo Máximo de Inferencia (ms)')),
                ('log_model_performance', models.BooleanField(default=False, help_text='Guardar métricas de rendimiento (para debugging)', verbose_name='Loggear Rendimiento')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='Histórico de tiempos de inferencia', verbose_name='Métricas de Rendimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('version', models.CharField(blank=True, default='v1.global', max_length=20, verbose_name='Versión')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Modelos',
                'verbose_name_plural': 'Configuraciones de Modelos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='enhancedmodelconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModelDefaults',
        ),
        migrations.DeleteModel(
            name='EnhancedModelConfig',
        ),
    ]
