# Generated by Django 5.2.1 on 2025-10-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_globalmodelconfig_remove_enhancedmodelconfig_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalModelConfig',
        ),
    ]
