# Generated by Django 5.2.1 on 2025-10-27 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0011_remove_globalmodelconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlinkEvent",
        ),
    ]
