# Generated by Django 5.2.1 on 2025-10-29 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0012_delete_blinkevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorsession",
            name="avg_focus_score",
            field=models.FloatField(
                blank=True,
                help_text="Score promedio de enfoque temporal (%)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="monitorsession",
            name="phone_detection_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Número de veces que se detectó uso de celular"
            ),
        ),
    ]
