# Generated by Django 5.2.1 on 2025-10-31 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0013_monitorsession_avg_focus_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMonitoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "microsleep_duration_seconds",
                    models.FloatField(
                        default=1.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.8),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Duración Microsueño (seg)",
                    ),
                ),
                (
                    "low_blink_rate_threshold",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Umbral Parpadeo Bajo (por min)",
                    ),
                ),
                (
                    "high_blink_rate_threshold",
                    models.PositiveSmallIntegerField(
                        default=35,
                        validators=[
                            django.core.validators.MinValueValidator(25),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Umbral Parpadeo Alto (por min)",
                    ),
                ),
                (
                    "yawn_mar_threshold",
                    models.FloatField(
                        default=0.6,
                        validators=[
                            django.core.validators.MinValueValidator(0.4),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Umbral Bostezo (MAR)",
                    ),
                ),
                (
                    "low_light_threshold",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Umbral Luz Baja (Luminancia)",
                    ),
                ),
                (
                    "monitoring_frequency",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Frecuencia de análisis (seg)",
                    ),
                ),
                (
                    "break_reminder_interval",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Recordatorio Descanso (min)",
                    ),
                ),
                (
                    "sampling_interval_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Intervalo Muestreo (seg)",
                    ),
                ),
                (
                    "camera_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Habilitar o deshabilitar el uso de la cámara.",
                        verbose_name="Cámara Habilitada",
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(default=False, verbose_name="Modo Oscuro"),
                ),
                (
                    "notification_mode",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("sound", "Sonora"),
                            ("both", "Ambos"),
                            ("none", "Ninguno"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="Modo de Notificación",
                    ),
                ),
                (
                    "alert_volume",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Volumen de Alertas",
                    ),
                ),
                (
                    "notify_inactive_tab",
                    models.BooleanField(
                        default=True,
                        help_text="Mostrar notificaciones cuando la pestaña no está activa.",
                        verbose_name="Notificar en Tab Inactiva",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones por correo electrónico.",
                        verbose_name="Notificaciones por Email",
                    ),
                ),
                (
                    "data_collection_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Autorizar recolección de datos para mejorar el servicio.",
                        verbose_name="Consentimiento Recolección Datos",
                    ),
                ),
                (
                    "anonymous_analytics",
                    models.BooleanField(
                        default=True,
                        help_text="Permitir analíticas anónimas para estadísticas generales.",
                        verbose_name="Analíticas Anónimas",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        default="es",
                        help_text="Código de idioma (ej: 'es', 'en', 'fr').",
                        max_length=10,
                        verbose_name="Idioma/Localización",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="America/Guayaquil",
                        help_text="Zona horaria del usuario (ej: 'America/Guayaquil').",
                        max_length=50,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
