# Generated by Django 5.2.1 on 2025-10-31 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0014_usermonitoringconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorsession",
            name="avg_head_roll",
        ),
        migrations.RemoveField(
            model_name="monitorsession",
            name="head_pose_variance",
        ),
    ]
