# Generated by Django 5.2.1 on 2025-10-31 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0015_remove_monitorsession_avg_head_roll_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorsession",
            name="avg_head_pitch",
        ),
        migrations.RemoveField(
            model_name="monitorsession",
            name="avg_head_yaw",
        ),
    ]
