# Generated by Django 5.2.1 on 2025-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0016_remove_monitorsession_avg_head_pitch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorsession",
            name="avg_mar",
        ),
        migrations.RemoveField(
            model_name="monitorsession",
            name="total_yawns",
        ),
        migrations.RemoveField(
            model_name="usermonitoringconfig",
            name="yawn_mar_threshold",
        ),
        migrations.AlterField(
            model_name="alertevent",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("fatigue", "Fatiga visual"),
                    ("distraction", "Distracción prolongada"),
                    ("low_light", "Iluminación baja"),
                    ("microsleep", "Microsueño detectado"),
                    ("low_blink_rate", "Tasa de parpadeo baja"),
                    ("high_blink_rate", "Tasa de parpadeo alta"),
                    ("frequent_distraction", "Distracción frecuente (ráfagas)"),
                    ("phone_use", "Posible uso de celular"),
                    ("postural_rigidity", "Rigidez postural / Mirada fija"),
                    ("head_agitation", "Movimiento excesivo de cabeza"),
                    ("driver_absent", "Usuario ausente"),
                    ("multiple_people", "Múltiples personas detectadas"),
                    ("camera_occluded", "Cámara obstruida"),
                    ("camera_lost", "Cámara perdida"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="alerttypeconfig",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("fatigue", "Fatiga visual"),
                    ("distraction", "Distracción prolongada"),
                    ("low_light", "Iluminación baja"),
                    ("microsleep", "Microsueño detectado"),
                    ("low_blink_rate", "Tasa de parpadeo baja"),
                    ("high_blink_rate", "Tasa de parpadeo alta"),
                    ("frequent_distraction", "Distracción frecuente (ráfagas)"),
                    ("phone_use", "Posible uso de celular"),
                    ("postural_rigidity", "Rigidez postural / Mirada fija"),
                    ("head_agitation", "Movimiento excesivo de cabeza"),
                    ("driver_absent", "Usuario ausente"),
                    ("multiple_people", "Múltiples personas detectadas"),
                    ("camera_occluded", "Cámara obstruida"),
                    ("camera_lost", "Cámara perdida"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
