# Generated by Django 5.2.1 on 2025-11-01 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_exercisestep_icon_class_and_more'),
        ('monitoring', '0017_remove_monitorsession_avg_mar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='auto_resolved',
            field=models.BooleanField(default=False, help_text='True si se resolvió automáticamente sin intervención del usuario', verbose_name='Auto-resuelta'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='exercise_session',
            field=models.ForeignKey(blank=True, help_text='Sesión de ejercicio realizada para resolver esta alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_alert', to='exercises.exercisesession', verbose_name='Sesión de Ejercicio'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='resolution_method',
            field=models.CharField(blank=True, choices=[('exercise', 'Ejercicio Completado'), ('dismissed', 'Descartada por el usuario'), ('timeout', 'Auto-cerrada por timeout'), ('improved', 'Condición mejorada automáticamente')], max_length=20, null=True, verbose_name='Método de Resolución'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='alert_type',
            field=models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distraction', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('microsleep', 'Microsueño detectado'), ('low_blink_rate', 'Tasa de parpadeo baja'), ('high_blink_rate', 'Tasa de parpadeo alta'), ('frequent_distraction', 'Distracción frecuente (ráfagas)'), ('phone_use', 'Posible uso de celular'), ('postural_rigidity', 'Rigidez postural / Mirada fija'), ('head_agitation', 'Movimiento excesivo de cabeza'), ('driver_absent', 'Usuario ausente'), ('multiple_people', 'Múltiples personas detectadas'), ('camera_occluded', 'Cámara obstruida'), ('camera_lost', 'Cámara perdida'), ('head_tension', 'Tensión en cuello'), ('micro_rhythm', 'Somnolencia temprana')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alerttypeconfig',
            name='alert_type',
            field=models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distraction', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('microsleep', 'Microsueño detectado'), ('low_blink_rate', 'Tasa de parpadeo baja'), ('high_blink_rate', 'Tasa de parpadeo alta'), ('frequent_distraction', 'Distracción frecuente (ráfagas)'), ('phone_use', 'Posible uso de celular'), ('postural_rigidity', 'Rigidez postural / Mirada fija'), ('head_agitation', 'Movimiento excesivo de cabeza'), ('driver_absent', 'Usuario ausente'), ('multiple_people', 'Múltiples personas detectadas'), ('camera_occluded', 'Cámara obstruida'), ('camera_lost', 'Cámara perdida'), ('head_tension', 'Tensión en cuello'), ('micro_rhythm', 'Somnolencia temprana')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='AlertExerciseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fatigue', 'Fatiga visual'), ('distraction', 'Distracción prolongada'), ('low_light', 'Iluminación baja'), ('microsleep', 'Microsueño detectado'), ('low_blink_rate', 'Tasa de parpadeo baja'), ('high_blink_rate', 'Tasa de parpadeo alta'), ('frequent_distraction', 'Distracción frecuente (ráfagas)'), ('phone_use', 'Posible uso de celular'), ('postural_rigidity', 'Rigidez postural / Mirada fija'), ('head_agitation', 'Movimiento excesivo de cabeza'), ('driver_absent', 'Usuario ausente'), ('multiple_people', 'Múltiples personas detectadas'), ('camera_occluded', 'Cámara obstruida'), ('camera_lost', 'Cámara perdida'), ('head_tension', 'Tensión en cuello'), ('micro_rhythm', 'Somnolencia temprana')], max_length=30, unique=True, verbose_name='Tipo de Alerta')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no se sugerirá el ejercicio para esta alerta', verbose_name='Activo')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 = Máxima prioridad, 10 = Mínima prioridad', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_mappings', to='exercises.exercise', verbose_name='Ejercicio Recomendado')),
            ],
            options={
                'verbose_name': 'Mapeo Alerta-Ejercicio',
                'verbose_name_plural': 'Mapeos Alerta-Ejercicio',
                'ordering': ['priority', 'alert_type'],
            },
        ),
    ]
