# Generated by Django 5.2.1 on 2025-11-02 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0018_alertevent_auto_resolved_alertevent_exercise_session_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttypeconfig",
            name="microsleep_duration",
            field=models.FloatField(
                blank=True,
                default=5.0,
                help_text="Duración en segundos para microsueño (5.0 a 15.0)",
                null=True,
                verbose_name="Duración Microsueño (segundos)",
            ),
        ),
        migrations.AlterField(
            model_name="usermonitoringconfig",
            name="microsleep_duration_seconds",
            field=models.FloatField(
                default=5.0,
                validators=[
                    django.core.validators.MinValueValidator(5.0),
                    django.core.validators.MaxValueValidator(15.0),
                ],
                verbose_name="Duración Microsueño (seg)",
            ),
        ),
    ]
