# Generated by Django 5.2.1 on 2025-11-02 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0019_alerttypeconfig_microsleep_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertevent",
            name="last_repeated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp de la última vez que se repitió",
                null=True,
                verbose_name="Última Repetición",
            ),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="repeat_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cuántas veces se ha repetido esta alerta",
                verbose_name="Número de Repeticiones",
            ),
        ),
        migrations.AddField(
            model_name="alerttypeconfig",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Tiempo mínimo entre alertas del mismo tipo",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Cooldown (segundos)",
            ),
        ),
        migrations.AddField(
            model_name="alerttypeconfig",
            name="repeat_max_per_hour",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Número máximo de repeticiones de este tipo de alerta por hora (0 = sin límite)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Máx. Repeticiones/Hora",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="alert_repeat_interval",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Tiempo en segundos para que la alerta vuelva a sonar hasta que sea resuelta (1-50 s)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="Intervalo Repetición Alertas (seg)",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="repeat_max_per_hour",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Número máximo de veces que una alerta puede repetirse en una hora",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Máximo Repeticiones por Hora",
            ),
        ),
        migrations.AlterField(
            model_name="alertevent",
            name="resolution_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ack", "Reconocida/Cerrada"),
                    ("exercise", "Ejercicio Completado"),
                    ("dismissed", "Descartada por el usuario"),
                    ("timeout", "Auto-cerrada por timeout"),
                    ("improved", "Condición mejorada automáticamente"),
                    ("auto", "Auto-resuelta"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de Resolución",
            ),
        ),
    ]
