# Generated by Django 5.2.1 on 2025-11-02 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_remove_notification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitoringconfig',
            name='ear_threshold',
            field=models.FloatField(default=0.2, help_text='Sensibilidad de apertura ocular. Más bajo = más sensible. (0.05 - 0.40)', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.4)], verbose_name='Umbral EAR (Eye Aspect Ratio)'),
        ),
        migrations.AddField(
            model_name='usermonitoringconfig',
            name='yawn_mar_threshold',
            field=models.FloatField(default=0.6, help_text='Sensibilidad de detección de bostezo. (0.4 - 1.0)', validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(1.0)], verbose_name='Umbral Bostezo (MAR - Mouth Aspect Ratio)'),
        ),
    ]
