# Generated by Django 5.2.1 on 2025-11-03 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0022_add_ear_yawn_thresholds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermonitoringconfig",
            name="high_blink_rate_threshold",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Por encima de 20-25 PPM se considera alto. (21-60 PPM)",
                validators=[
                    django.core.validators.MinValueValidator(21),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Umbral Parpadeo Alto (por min)",
            ),
        ),
        migrations.AlterField(
            model_name="usermonitoringconfig",
            name="low_blink_rate_threshold",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Por debajo de 10 PPM se considera bajo. (3-14 PPM)",
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(14),
                ],
                verbose_name="Umbral Parpadeo Bajo (por min)",
            ),
        ),
    ]
