# Generated by Django 5.2.1 on 2025-11-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_feedback_field'),
        ('monitoring', '0023_alter_usermonitoringconfig_high_blink_rate_threshold_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['triggered_at'], name='monitoring__trigger_c4a576_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['session', 'triggered_at'], name='monitoring__session_47d747_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert_type', 'triggered_at'], name='monitoring__alert_t_ff446a_idx'),
        ),
    ]
