# Generated by Django 5.2.1 on 2025-11-09 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_add_alert_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttypeconfig',
            name='detection_delay',
            field=models.FloatField(blank=True, default=5.0, help_text='Tiempo en segundos antes de activar la alerta (5.0 a 60.0)', null=True, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(60.0)], verbose_name='Retraso de Detección (segundos)'),
        ),
        migrations.AddField(
            model_name='alerttypeconfig',
            name='hysteresis_timeout',
            field=models.FloatField(blank=True, default=30.0, help_text='Tiempo máximo para resolver la alerta antes de pausar el monitoreo', null=True, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Tiempo de Histéresis (segundos)'),
        ),
        migrations.AddField(
            model_name='alerttypeconfig',
            name='max_repetitions',
            field=models.IntegerField(default=1, help_text='Número máximo de repeticiones antes de pausar (1 para alertas con histéresis)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máximo de Repeticiones'),
        ),
    ]
