# Generated by Django 5.2.1 on 2025-11-09 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_alerttypeconfig_detection_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttypeconfig',
            name='threshold_high',
            field=models.FloatField(blank=True, default=40.0, help_text='Umbral para alertas de tipo "alto" (ejemplo: tasa de parpadeo alta)', null=True, validators=[django.core.validators.MinValueValidator(15.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Umbral Alto'),
        ),
    ]
