# Generated by Django 5.2.1 on 2025-11-09 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_alerttypeconfig_threshold_high'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermonitoringconfig',
            name='yawn_mar_threshold',
        ),
        migrations.AlterField(
            model_name='alerttypeconfig',
            name='repeat_max_per_hour',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de veces que se solicitará realizar el ejercicio antes de pausar el monitoreo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máx. Repeticiones Ejercicio'),
        ),
    ]
