# Generated by Django 5.2.1 on 2025-11-09 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_remove_usermonitoringconfig_yawn_mar_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttypeconfig',
            name='repeat_max_per_hour',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de repeticiones antes de pausar o ejercicios requeridos (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máximo de Repeticiones'),
        ),
    ]
