# Generated by Django 5.2.1 on 2025-11-09 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0028_alter_alerttypeconfig_repeat_max_per_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerttypeconfig",
            name="repeat_max_per_hour",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Para alertas con pausa: número de repeticiones antes de pausar. Para alertas con ejercicios: veces que se mostrará la notificación antes de desaparecer.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Máximo de Repeticiones",
            ),
        ),
    ]
