# Generated by Django 5.2.1 on 2025-11-09 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0029_alter_alerttypeconfig_repeat_max_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttypeconfig",
            name="resolution_type",
            field=models.CharField(
                choices=[
                    ("exercise", "Ejercicio"),
                    ("hysteresis", "Histéresis"),
                    ("auto_pause", "Auto-Pausa"),
                    ("dismiss", "Descartar"),
                ],
                default="exercise",
                help_text="Cómo se resuelve la alerta",
                max_length=20,
                verbose_name="Tipo de Resolución",
            ),
        ),
        migrations.AlterField(
            model_name="alerttypeconfig",
            name="hysteresis_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Para resolución por histéresis: tiempo que debe mantenerse la condición OK",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(1800),
                ],
                verbose_name="Tiempo para Resolución (seg)",
            ),
        ),
    ]
