# Generated by Django 5.2.1 on 2025-11-09 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0031_alerttypeconfig_metadata_alter_alertevent_alert_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerttypeconfig",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                default=10,
                help_text="Tiempo mínimo entre alertas del mismo tipo. Null para alertas sin cooldown.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Cooldown (segundos)",
            ),
        ),
    ]
