# Generated by Django 5.2.1 on 2025-11-09 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0032_alter_alerttypeconfig_cooldown_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="alert_cooldown_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Tiempo mínimo entre alertas del mismo tipo para el usuario",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(3600),
                ],
                verbose_name="Cooldown de Alertas (seg)",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="detection_delay_seconds",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Tiempo que debe mantenerse la condición antes de activar la alerta",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3600),
                ],
                verbose_name="Retraso de Detección (seg)",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="hysteresis_timeout_seconds",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Tiempo que debe mantenerse la condición OK para considerar resuelta (histéresis)",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(3600),
                ],
                verbose_name="Tiempo de Histéresis (seg)",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="resolution_type",
            field=models.CharField(
                choices=[
                    ("exercise", "Ejercicio"),
                    ("hysteresis", "Histéresis"),
                    ("auto_pause", "Auto-Pausa"),
                    ("dismiss", "Descartar"),
                ],
                default="exercise",
                help_text="Cómo se resolverán por defecto las alertas para este usuario",
                max_length=20,
                verbose_name="Tipo de Resolución por Defecto",
            ),
        ),
        migrations.AddField(
            model_name="usermonitoringconfig",
            name="threshold_high",
            field=models.FloatField(
                blank=True,
                help_text="Umbral genérico alto para ciertos tipos de alerta (opcional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Umbral Alto",
            ),
        ),
    ]
