# Generated by Django 5.2.1 on 2025-11-09 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0033_usermonitoringconfig_alert_cooldown_seconds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermonitoringconfig",
            name="resolution_type",
        ),
        migrations.RemoveField(
            model_name="usermonitoringconfig",
            name="threshold_high",
        ),
    ]
