# Generated by Django 5.2.1 on 2025-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0034_remove_usermonitoringconfig_resolution_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="cooldown_seconds",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="detection_delay",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="hysteresis_timeout",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="max_repetitions",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="microsleep_duration",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="repeat_max_per_hour",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="resolution_type",
        ),
        migrations.RemoveField(
            model_name="alerttypeconfig",
            name="threshold_high",
        ),
        migrations.AlterField(
            model_name="alertexercisemapping",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("fatigue", "Fatiga visual"),
                    ("distraction", "Distracción prolongada"),
                    ("low_light", "Iluminación baja"),
                    ("microsleep", "Microsueño detectado"),
                    ("low_blink_rate", "Tasa de parpadeo baja"),
                    ("high_blink_rate", "Tasa de parpadeo alta"),
                    ("frequent_distraction", "Distracción frecuente (ráfagas)"),
                    ("phone_use", "Posible uso de celular"),
                    ("postural_rigidity", "Rigidez postural / Mirada fija"),
                    ("head_agitation", "Movimiento excesivo de cabeza"),
                    ("driver_absent", "Usuario ausente"),
                    ("multiple_people", "Múltiples personas detectadas"),
                    ("camera_occluded", "Cámara obstruida"),
                    ("camera_lost", "Cámara perdida"),
                    ("head_tension", "Tensión en cuello"),
                    ("micro_rhythm", "Somnolencia temprana"),
                    ("bad_posture", "Postura incorrecta"),
                    ("bad_distance", "Distancia incorrecta"),
                    ("strong_glare", "Reflejo excesivo"),
                    ("strong_light", "Luz excesiva"),
                ],
                max_length=30,
                unique=True,
                verbose_name="Tipo de Alerta",
            ),
        ),
        migrations.AlterField(
            model_name="alerttypeconfig",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Metadatos adicionales (no umbrales/tiempos)",
                null=True,
            ),
        ),
    ]
