# Generated by Django 5.2.1 on 2025-11-11 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0036_alter_alertevent_alert_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorsession",
            name="phone_detection_count",
        ),
    ]
