# Generated by Django 5.2.1 on 2025-11-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0037_remove_phone_detection_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorsession",
            name="alerts_count",
        ),
        migrations.RemoveField(
            model_name="monitorsession",
            name="total_alerts",
        ),
        migrations.AlterField(
            model_name="monitorsession",
            name="alert_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Número total de alertas durante la sesión"
            ),
        ),
    ]
