# Generated by Django 5.2.1 on 2025-10-18 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('target', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Finalizado')], default='pending', max_length=12)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Borrado de Datos',
                'verbose_name_plural': 'Solicitudes de Borrado de Datos',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='reports/cache/')),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cache de Reporte',
                'verbose_name_plural': 'Caches de Reporte',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_from', models.DateTimeField(blank=True, null=True)),
                ('period_to', models.DateTimeField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, help_text='Filtros y agregaciones', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('ready', 'Listo'), ('failed', 'Error')], default='pending', max_length=12)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='ID del worker (celery/rq)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Reporte',
                'verbose_name_plural': 'Solicitudes de Reporte',
                'ordering': ['-requested_at'],
            },
        ),
    ]
